name: run-textlint
on:
  # push:
  #   branches:
  #     - main
  pull_request_target:
    types: [opened, synchronize]
    paths: 
      - '**/*.md'
      - '**/*.txt'

jobs:
  run-textlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.TOKEN }}

      - name: Setup node with cache
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Install packages via package.json
        run: npm install

      - name: Run textlint (avoiding error)
        run: |
          npx textlint "**/*.md" "**/*.txt" -o ./.textlint.log || true
        shell: bash

      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Report if textlint finds problems
        run: |
          if [ -f ./.textlint.log ]; then
            # Adjust paths in the log
            sed -i "s|$(pwd)|### :policeman: |g" ./.textlint.log
            # Post comment to PR
            gh pr comment ${{ github.event.pull_request.html_url }} --body "$(cat ./.textlint.log)"
          fi
